set_property PACKAGE_PIN P17 [get_ports clk]
set_property PACKAGE_PIN P15 [get_ports rst_n]

set_property PACKAGE_PIN B1 [get_ports {a_to_g[4]}]
set_property PACKAGE_PIN A3 [get_ports {a_to_g[5]}]
set_property PACKAGE_PIN A4 [get_ports {a_to_g[6]}]
set_property PACKAGE_PIN B4 [get_ports {a_to_g[7]}]
set_property PACKAGE_PIN H4 [get_ports {a_to_g[8]}]
set_property PACKAGE_PIN D2 [get_ports {a_to_g[9]}]
set_property PACKAGE_PIN E2 [get_ports {a_to_g[10]}]
set_property PACKAGE_PIN F3 [get_ports {a_to_g[11]}]
set_property PACKAGE_PIN F4 [get_ports {a_to_g[12]}]
set_property PACKAGE_PIN D3 [get_ports {a_to_g[13]}]
set_property PACKAGE_PIN E3 [get_ports {a_to_g[14]}]
set_property PACKAGE_PIN D4 [get_ports {a_to_g[15]}]
set_property PACKAGE_PIN A1 [get_ports {a_to_g[3]}]
set_property PACKAGE_PIN B3 [get_ports {a_to_g[2]}]
set_property PACKAGE_PIN B2 [get_ports {a_to_g[1]}]
set_property PACKAGE_PIN D5 [get_ports {a_to_g[0]}]

set_property PACKAGE_PIN G2 [get_ports {an[7]}]
set_property PACKAGE_PIN C2 [get_ports {an[6]}]
set_property PACKAGE_PIN C1 [get_ports {an[5]}]
set_property PACKAGE_PIN H1 [get_ports {an[4]}]
set_property PACKAGE_PIN G1 [get_ports {an[3]}]
set_property PACKAGE_PIN F1 [get_ports {an[2]}]
set_property PACKAGE_PIN E1 [get_ports {an[1]}]
set_property PACKAGE_PIN G6 [get_ports {an[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports echo]
set_property IOSTANDARD LVCMOS33 [get_ports kaiguan_1]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports trig]
set_property PACKAGE_PIN H17 [get_ports trig]
set_property PACKAGE_PIN P5 [get_ports kaiguan_1]




set_property IOSTANDARD LVCMOS33 [get_ports bee]
set_property PACKAGE_PIN G17 [get_ports bee]
set_property PACKAGE_PIN K13 [get_ports echo]

set_property PACKAGE_PIN P4 [get_ports kaiguan_2]
set_property IOSTANDARD LVCMOS33 [get_ports kaiguan_2]
